name: reLCS premake linux amd64

on:
  pull_request:
  push:
  release:
    types: published
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-amd64-librw_gl3_glfw-oal]
        buildtype: [Debug, Release]
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: 'true'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libopenal-dev libglew-dev libglfw3-dev libsndfile1-dev libmpg123-dev
    - name: Configure build
      run: |
        chmod +x ./premake5Linux
        ./premake5Linux --with-librw --no-git-hash gmake2
    - name: Build
      run: |
        make -C build -j$(nproc) config=$(echo ${{matrix.buildtype}} | tr '[:upper:]' '[:lower:]')_${{matrix.platform}}
    - name: Move binaries to gamefiles
      run: |
        mkdir -p ./gamefiles
        cp ./bin/${{matrix.platform}}/${{matrix.buildtype}}/reLCS ./gamefiles/
    - name: Upload artifact to actions
      uses: actions/upload-artifact@v7
      with:
        name: reLCS_${{matrix.buildtype}}_${{matrix.platform}}
        path: ./gamefiles/*
